name: Deploy Theme
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.0
        with:
          api-url: '${{ secrets.ADMIN_URL }}'
          api-key: '${{ secrets.ADMIN_KEY }}'
